apiVersion: {{ .Values.rbacApiVersion }}/v1
kind: ClusterRole
metadata:
  name: system:controller:operator-lifecycle-manager
  {{- if and .Values.installType (eq .Values.installType "ocp") }}
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  {{- end }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: olm-operator-serviceaccount
  namespace: {{ .Values.namespace }}
  {{- if and .Values.installType (eq .Values.installType "ocp") }}
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  {{- end }}
---
apiVersion: {{ .Values.rbacApiVersion }}/v1
kind: ClusterRoleBinding
metadata:
  name: olm-operator-binding-{{ .Values.namespace }}
  {{- if and .Values.installType (eq .Values.installType "ocp") }}
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  {{- end }}

roleRef:
  apiGroup: {{ .Values.rbacApiVersion }}
  kind: ClusterRole
  name: system:controller:operator-lifecycle-manager
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: {{ .Values.namespace }}
