{{- if .Values.imagestream }}
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: {{ .Values.writeStatusName }}
  {{- if and .Values.installType (eq .Values.installType "ocp") }}
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  {{- end }}
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: {{ .Values.writeStatusNameCatalog }}
  {{- if and .Values.installType (eq .Values.installType "ocp") }}
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  {{- end }}
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
{{- if .Values.writePackageServerStatusName }}
---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: {{ .Values.writePackageServerStatusName }}
  {{- if and .Values.installType (eq .Values.installType "ocp") }}
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  {{- end }}
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
{{- end }}      
{{- end }}
